# Generated by Django 3.1.6 on 2021-06-12 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson', '0005_userprofile_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='')),
                ('option_1', models.CharField(default='', max_length=300)),
                ('option_2', models.CharField(default='', max_length=300)),
                ('option_3', models.CharField(default='', max_length=300)),
                ('option_4', models.CharField(default='', max_length=300)),
                ('answer', models.CharField(default='NA', max_length=200)),
                ('in_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lesson.lesson')),
            ],
        ),
    ]
