# Generated by Django 3.1.6 on 2021-06-12 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_userprofile_points'),
        ('MCQs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='in_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lesson.lesson'),
        ),
    ]
