# Generated by Django 3.1.6 on 2021-06-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCQs', '0005_auto_20210612_2309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attempts',
        ),
    ]
