# Generated by Django 3.1.6 on 2021-06-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='intro',
            name='intro_title',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
