# Generated by Django 3.1.6 on 2021-06-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20210612_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='intro',
            name='intro_title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
