# Generated by Django 3.1.6 on 2021-06-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_userprofile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
