# Generated by Django 3.1.6 on 2021-06-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_userprofile_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='attempts',
        ),
    ]
